# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7fn_aypjH58i_gLTCOOYh9d1_hpBklQ
"""

!pip install shap

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier

import shap

df = pd.read_csv("credit_risk_dataset.csv")
df.head()

df.shape          # rows, columns
df.info()         # types + missing values
df.describe()     # stats for numerical columns
df.isnull().sum() # count missing values per column

df["loan_status"].value_counts(normalize=True)

num_cols = ["person_age", "person_income", "loan_amnt", "loan_int_rate", "loan_percent_income", "cb_person_cred_hist_length"]  # change to match your dataset

df[num_cols].hist(figsize=(10,8))
plt.tight_layout()
plt.show()

df.groupby("loan_status")["person_income"].mean()
df.groupby("loan_status")["loan_amnt"].mean()

# Example: fill missing numeric with median
num_cols = df.select_dtypes(include=["int64", "float64"]).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# For categorical columns, fill with mode
cat_cols = df.select_dtypes(include=["object"]).columns
df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])

df_encoded = pd.get_dummies(df, drop_first=True)
df_encoded.head()

X = df_encoded.drop("loan_status", axis=1)
y = df_encoded["loan_status"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

model = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

print("ROC-AUC:", roc_auc_score(y_test, y_proba))
print(classification_report(y_test, y_pred))

from sklearn.metrics import ConfusionMatrixDisplay

ConfusionMatrixDisplay.from_estimator(model, X_test, y_test)
plt.show()

shap.initjs()

explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_train)


shap.summary_plot(shap_values, X_train)

shap.summary_plot(shap_values, X_train, plot_type="bar")

X_test_sample = X_test.copy()
X_test_sample.reset_index(drop=True, inplace=True)

index = 0  # change 0 to other indices to see different customers
x = X_test_sample.iloc[index]
x

shap_value_single = explainer.shap_values(x)

# Corrected calls
shap.force_plot(explainer.expected_value[0], shap_value_single, x)

shap.plots._waterfall.waterfall_legacy(
    explainer.expected_value[0], shap_value_single, feature_names=x.index
)

interaction_values = explainer.shap_interaction_values(X_train)

shap.summary_plot(interaction_values, X_train)

shap.dependence_plot(
    "loan_percent_income", shap_values, X_train, interaction_index="loan_amnt"
)

explainer_all = shap.TreeExplainer(model)
shap_values_all = explainer_all.shap_values(X)

shap_sum = shap_values_all.sum(axis=1)  # total contribution for each person

df_fairness = df.copy()
df_fairness["model_output"] = model.predict_proba(X)[:,1]
df_fairness["shap_sum"] = shap_sum

df_fairness.groupby("person_home_ownership")[["model_output", "shap_sum"]].mean()

